#! /bin/sh

sxhkd &
unclutter &
setxkbmap -option caps:escape
xset b off
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr
feh --bg-fill $HOME/.config/bspwm/wall.jpg
picom --config $HOME/.config/bspwm/picom.conf --experimental-backends &

$HOME/.config/bspwm/panel.sh
